/*


Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate
(polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  		P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits 
	of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal
	(P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which
each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal,
is represented by a different number in the set.

*/

#include <iostream>
#include <tuple>
#include <ttmath\ttmath.h>
using namespace std ;

unsigned long long P( int i, unsigned long long n )
{
	switch ( i )
	{
	case 3:
		return ( n * ( n + 1 ) ) / 2 ;
	case 4:
		return n * n ;
	case 5:
		return ( n * ( 3 * n - 1 ) ) / 2 ;
	case 6:
		return n * ( 2 * n - 1 ) ;
	case 7:
		return ( n * ( 5 * n - 3 ) ) / 2 ;
	case 8:
		return n * ( 3 * n - 2 ) ;
	default:
		cerr << "Fehler: Falsche Eingabe!" << endl ;
		return 0 ;
	}
}

void hinzufuegen( vector< tuple< string, string, string, int > >& Ps, int n, int k )
{
	unsigned long long erg = P( k, n ) ;
	string gesamt = to_string( erg ) ;
	string anfang = gesamt.substr( 0, 2 ) ;
	string ende = gesamt.substr( 2, 2 ) ;
		
	tuple< string, string, string, int > neu( anfang, gesamt, ende, k ) ;
	Ps.push_back( neu ) ;
}

bool enthalten( tuple< string, string, string, int >& e, vector< tuple< string, string, string, int > >& loesung )
{
	for ( int i = 0 ;  i < loesung.size() ;  ++i )
		if ( get< 1 >( loesung.at( i ) ) == get< 1 >( e ) || get< 3 >( loesung.at( i ) ) == get< 3 >( e ) )
			return true ;

	return false ;
}

bool loese( vector< tuple< string, string, string, int > >& loesung, vector< tuple< string, string, string, int > >& Ps )
{
	if ( loesung.size() == 6 )
	{
		if ( get< 0 >( loesung.at( 0 ) ) == get< 2 >( loesung.at( loesung.size() - 1 ) ) )
			return true ;
	}

	for ( int i = 0 ;  i < Ps.size() ;  ++i )
		if ( get< 2 >( loesung.at( loesung.size() - 1 ) ) == get< 0 >( Ps.at( i ) ) && !enthalten( Ps.at( i ), loesung ) )
		{
			loesung.push_back( Ps.at( i ) ) ;
			if ( loese( loesung, Ps ) )
				return true ;

			loesung.pop_back() ;
		}

	return false ;
}

int main ()
{
	// tuple< Anfang, Gesamt, Ende, Gruppe >
	vector< tuple< string, string, string, int > > Ps ;

	for ( int n = ceil( 0.5 * ( 3 * sqrt( 889. ) - 1 ) ) ;  n <= floor( 0.5 * ( sqrt( 79993. ) - 1 ) ) ;  ++n )
		hinzufuegen( Ps, n, 3 ) ;

	for ( int n = ceil( 10 * sqrt( 10. ) ) ;  n <= floor( 3 * sqrt( 1111. ) ) ;  ++n )
		hinzufuegen( Ps, n, 4 ) ;

	for ( int n = ceil( ( 1/6. ) * ( 1 + sqrt( 24001. ) ) ) ;  n <= floor( ( 1/6. ) * ( 1 + sqrt( 239977. ) ) ) ;  ++n )
		hinzufuegen( Ps, n, 5 ) ;

	for ( int n = ceil( ( 1/4. ) * ( 1 + 3 * sqrt( 889. ) ) ) ;  n <= floor( ( 1/4. ) * ( 1 + sqrt( 79993. ) ) ) ;  ++n )
		hinzufuegen( Ps, n, 6 ) ;

	for ( int n = ceil( 0.1 * ( 3 + sqrt( 40009. ) ) ) ;  n <= floor( ( 3/10. ) * ( 1 + sqrt( 44441. ) ) ) ;  ++n )
		hinzufuegen( Ps, n, 7 ) ;

	for ( int n = ceil( ( 1 / 3. ) * ( 1 + sqrt( 3001. ) ) ) ;  n <= floor( ( 1/3. ) * ( 1 + sqrt( 29998. ) ) ) ;  ++n )
		hinzufuegen( Ps, n, 8 ) ;

	vector< tuple< string, string, string, int > > loesung ;

	for ( int i = 0 ;  i < Ps.size() ;  ++i )
	{
		loesung.push_back( Ps.at( i ) ) ;
		if ( loese( loesung, Ps ) )
			break ;
		loesung.clear() ;
	}
	

	int summe = 0 ;
	for ( int i = 0 ;  i < loesung.size() ;  ++i )
		summe += atoi( get< 1 >( loesung.at( i ) ).c_str() ) ;

	cout << summe << endl ;
	
	return 0 ;
}